#############################################################################
## Server configuration
#############################################################################
server:
  port: ${PORT:3000}
